### PR TITLE
Dynamically populate profile card info

### PR DESCRIPTION
**Pull request by eternal44**
Facebook & origin column missing.  Still populating those pages with
fill-in data.

Also wasn't sure how to cycle through three tag colors so used two instead.

### CODE REVIEW

**Comment by eternal44** [comment]
@jamestyack @ybentz @philril - your feedback is always welcome if you have any!  

Also, I just realized I should probably source in data more dynamically for the profile card so we can also use the directive in our story page as well.  I came across [this solution](http://stackoverflow.com/questions/24762229/dynamic-ng-controller-name) which creates a global directive and controller but seems a little messy...  any suggestions?

**Comment by jamestyack** [comment]
nice! and travis passed (was failing on a PR a couple of days ago).  I'll merge... maybe we should just remove that facebook link @grodeska ?

**Comment by danrasmuson** [comment]
Pass in the profile obj as an attribute on the directive.

**Comment by danrasmuson** [comment]
@eternal44

**Pull request merged**
